// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SentisFlatBuffer
{

enum InstructionArguments : byte
{
  NONE = 0,
  KernelCall = 1,
};



static class InstructionArgumentsVerify
{
  static public bool Verify(Unity.Sentis.Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((InstructionArguments)typeId)
    {
      case InstructionArguments.KernelCall:
        result = SentisFlatBuffer.KernelCallVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
