// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SentisFlatBuffer
{

enum KernelTypes : byte
{
  NONE = 0,
  Null = 1,
  Int = 2,
  Float = 3,
  Bool = 4,
  Byte = 5,
  Tensor = 6,
  String = 7,
  IntList = 8,
  FloatList = 9,
  BoolList = 10,
};



static class KernelTypesVerify
{
  static public bool Verify(Unity.Sentis.Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((KernelTypes)typeId)
    {
      case KernelTypes.Null:
        result = SentisFlatBuffer.NullVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Int:
        result = SentisFlatBuffer.IntVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Float:
        result = SentisFlatBuffer.FloatVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Bool:
        result = SentisFlatBuffer.BoolVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Byte:
        result = SentisFlatBuffer.ByteVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Tensor:
        result = SentisFlatBuffer.TensorVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.String:
        result = SentisFlatBuffer.StringVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.IntList:
        result = SentisFlatBuffer.IntListVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.FloatList:
        result = SentisFlatBuffer.FloatListVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.BoolList:
        result = SentisFlatBuffer.BoolListVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
