// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SentisFlatBuffer
{

enum ScalarType : sbyte
{
  FLOAT = 0,
  INT = 1,
  BYTE = 2,
  SHORT = 3,
};


}
