// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SentisFlatBuffer
{

enum SymbolicDim : byte
{
  NONE = 0,
  Int = 1,
  Byte = 2,
};



static class SymbolicDimVerify
{
  static public bool Verify(Unity.Sentis.Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((SymbolicDim)typeId)
    {
      case SymbolicDim.Int:
        result = SentisFlatBuffer.IntVerify.Verify(verifier, tablePos);
        break;
      case SymbolicDim.Byte:
        result = SentisFlatBuffer.ByteVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}


}
