// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SentisFlatBuffer
{

enum TensorShapeDynamism : sbyte
{
  STATIC = 0,
  DYNAMIC_UNBOUND = 1,
};


}
